### ISSUE TITLE
No new .dll? Scale settings resetting in story mode (Koikatsu)

### ISSUE THREAD

**Issue by masamunewg** [ManlyMarco/KKABMX#12]
Where is it? Downloaded KKABMX-master and it's not in any folder.
I have the most updated .DLL from the "releases" section. Is that it? Was hoping for a further update.

There seems to be an issue in Koikatsu where the scaling settings do not carry over into "Story" mode at all. When I goto "Edit character" from "Class" in story mode, all the BonemodX scale settings have reverted to default. All other mods settings are persisting.

**Comment by ManlyMarco** [comment]
Latest stable releases are always in the releases section. Make sure that there are no errors in console/log that might prevent abmx from working correctly in class maker, some other plugin might be interferring.
