### ISSUE TITLE
Add option/slider for adjusting X, Y, Z together

### ISSUE THREAD

**Issue by AKSoo** [ManlyMarco/KKABMX#4]
Like left/right options, it would be very convenient to be able to adjust the whole scale of body parts.

This could work as sets of sliders at the top/bottom of pages or as tick box options.

**Comment by ManlyMarco** [comment]
Hello, and thank you for the suggestion!

Yes, it can be a bit tedious to do this. I looked into this and sadly it would either make the interface more bulky (additional checkbox for each of the XYZ slider groups), or require a complex UI setup that would take a lot of work.

It could be added to advanced mode, but then the question is how would it work, and if it would it be any faster than Ctrl+C and Ctrl+V twice in other fields.

That being said I'm open to suggestions how this could be done, maybe there is some good way I didn't think of.

**Comment by jojorne** [comment]
https://github.com/ManlyMarco/KKABMX/pull/8

**Comment by ManlyMarco** [comment]
Added in #9
