### ISSUE TITLE
Weird stutter when adjusting sliders

### ISSUE THREAD

**Issue by Michpem** [ManlyMarco/KKABMX#6]
Hello! I noticed a small (but quite annoying) bug with the newest build of the plugin: when I adjust a body slider, the character starts stuttering in a weird way, making it very hard to tell the difference between small edits. It seems like the bones or the entire model is being reloaded for every change.

Here's a video of what happens:

https://i.imgur.com/Ykrk66L.mp4

This doesn't happen with version 3.2.2. I'm also fully updated when it comes to the other plugins (Bepis, KKPE, etc).

**Comment by ManlyMarco** [comment]
Can you try this version? Would be great if you checked if other things work correctly too.
[KKABMX.zip](https://github.com/ManlyMarco/KKABMX/files/3369173/KKABMX.zip)

**Comment by Michpem** [comment]
That one seems to work correctly! I also tried testing all the extra sliders and they don't cause any trouble (well, other than the expected ones in Studio for messing too much with them).

**Comment by ManlyMarco** [comment]
Nice, the fix will be included in the next release.
